services:

  node_app_cep_consult:
    container_name: node_app_cep_consult
    build: ./back-end
    ports:
      - 5000:5000

  react_app_cep_consult:
    build: ./front-end
    container_name: react_app_cep_consult
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node_app_cep_consult

  nginx_cep_consult:
    build: ./nginx
    container_name: nginx_cep_consult
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node_app_cep_consult
      - react_app_cep_consult

volumes:
  build_react: